apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-access-binding
  namespace: system-namespace
subjects:
- kind: ServiceAccount
  name: data-service-sa
  namespace: app-namespace
roleRef:
  kind: Role
  name: minio-access-role
  apiGroup: rbac.authorization.k8s.io
