apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio-access-role
  namespace: system-namespace
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["minio-credentials"]
  verbs: ["get"]
