#After applying network policy only from app-system namespace and label app: data-service can access minio
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: app-system
type: Opaque
data:
  # These are base64 encoded values for "minioadmin" and "minioadmin"
  accesskey: bWluaW9hZG1pbg==
  secretkey: bWluaW9hZG1pbg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: data-service
  name: minio-test-data2
  namespace: app-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: data-service
    spec:
      containers:
      - command:
        - sleep
        - "100000000000000"
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: minio-credentials
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: minio-credentials
        - name: DATA_SERVICE_USER
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: data-service-minio-creds
        - name: DATA_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: data-service-minio-creds
        - name: AUTH_SERVICE_USER
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: auth-service-minio-creds
        - name: AUTH_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: auth-service-minio-creds
        image: minio/mc
        imagePullPolicy: Always
        name: mc
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30