apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: app-namespace
spec:
  selector:
    app: data-service
  ports:
  - port: 80
    targetPort: 5678
  type: ClusterIP
