apiVersion: v1
kind: Namespace
metadata:
  name: app-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-service-sa
  namespace: app-system
---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-minio-creds
  namespace: storage-system  
type: Opaque
data:
  accesskey: ZGF0YS1zZXJ2aWNlLWFjY2Vzcw==
  secretkey: ZGF0YS1zZXJ2aWNlLXNlY3JldA==
---
# ServiceAccount for auth-service (will not have access)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: app-system