apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: app-system
spec:
  selector:
    matchLabels:
      app: data-service
  replicas: 1
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: hashicorp/http-echo
        args:
        - "-text=Hello from data-service"
        ports:
        - containerPort: 5678
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: data-service-minio-creds
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: data-service-minio-creds
              key: secretkey
        - name: MINIO_ENDPOINT
          value: "http://minio.storage-system:9000"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: system
spec:
  selector:
    app: data-service
  ports:
  - port: 80
    targetPort: 5678
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: app-system
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: auth-service-sa
      containers:
      - name: auth-service
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /status/200
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /status/200
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: app-namespace
spec:
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
