apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  namespace: storage-system
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Configure MinIO client
          mc alias set myminio http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
          
          # Create a bucket
          mc mb myminio/app-data
          
          # Create user for data-service
          mc admin user add myminio data-service-user "$DATA_SERVICE_PASSWORD"
          
          # Create policy for data-service
          echo '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": ["s3:*"],
                "Resource": ["arn:aws:s3:::app-data/*"]
              }
            ]
          }' > /tmp/data-service-policy.json
          
          mc admin policy add myminio data-service-policy /tmp/data-service-policy.json
          
          # Apply policy to data-service user
          mc admin policy set myminio data-service-policy user=data-service-user
          
          echo "MinIO setup completed"
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: accesskey
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secretkey
        - name: DATA_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-service-minio-creds
              key: secretkey
      restartPolicy: OnFailure